server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/eureka/
    #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)

spring:
    application:
      name: member-productor
    datasource:
      url: jdbc:mysql://localhost:3305/use?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: hejianliang
      driver-class-name: com.mysql.cj.jdbc.Driver
    kafka:
      bootstrap-servers: 192.168.1.3:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        group-id: 0
        enable-auto-commit: true
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        client-id: 0
#dubbo:
#  application:
#    name: member
#  protocol:
#    name: dubbo
#    port: 20881
#  registry:
#    address: zookeeper://127.0.0.1:2181
#  scan:
mybatis:
  mapper-locations:  classpath:mapping/*Mapping.xml
#    base-packages: com.kkhjl.cloud.member.api