server:
  port: 8081
  servlet:
    context-path: /member
spring:
    datasource:
      url: jdbc:mysql://localhost:3305/use?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: hejianliang
      driver-class-name: com.mysql.cj.jdbc.Driver
    kafka:
      bootstrap-servers: 192.168.43.130:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        group-id: 0
        enable-auto-commit: true
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        client-id: 0
#dubbo:
#  application:
#    name: member
#  protocol:
#    name: dubbo
#    port: 20881
#  registry:
#    address: zookeeper://127.0.0.1:2181
#  scan:
mybatis:
  mapper-locations:  classpath:mapping/*Mapping.xml
#    base-packages: com.kkhjl.cloud.member.api