server:
  port: 80
  servlet:
    context-path: /zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/eureka/
    #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)

spring:
    application:
      name: cloud-zuul
zuul:
  routes:
     member:
          path: /member/**
          serviceId: member-productor
     test:
        path: /test/**
        url: http://baidu.com

