server:
  port: 8761
  servlet:
    context-path: /eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false  ##表示是否将自己注册到Eureka Server，默认是true。
    fetch-registry: false       ##表示是否从Eureka Server获取注册信息，默认为true。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka
